/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    GridHeader: typeof import('./src/components/weather/GridHeader.vue')['default']
    LocationManager: typeof import('./src/components/weather/LocationManager.vue')['default']
    PWABadge: typeof import('./src/components/PWABadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    WeatherBox: typeof import('./src/components/weather/WeatherBox.vue')['default']
    WeatherGrid: typeof import('./src/components/weather/WeatherGrid.vue')['default']
  }
}
