import type { BMKGResponse } from '@/types/weather'

const BMKG_API_BASE = 'https://weather.bmkg.go.id/api/df/v1/forecast/coord'
const API_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFjNWFkZWUxYzY5MzM0NjY2N2EzZWM0MWRlMjBmZWZhNDcxOTNjYzcyZDgwMGRiN2ZmZmFlMWVhYjcxZGYyYjQiLCJpYXQiOjE3MDE1ODMzNzl9.D1VNpMoTUVFOUuQW0y2vSjttZwj0sKBX33KyrkaRMcQ'

export class BMKGApiService {
  async getForecast(lat: number, lon: number): Promise<BMKGResponse> {
    const url = `${BMKG_API_BASE}?lat=${lat}&lon=${lon}`

    try {
      const response = await fetch(url, {
        method: 'GET',
        headers: {
          accept: 'application/json, text/plain, */*',
          'accept-language': 'en-US,en;q=0.9',
          'Alt-Used': 'cuaca.bmkg.go.id',
          'Cache-Control': 'no-cache',
          priority: 'u=1, i',
          Pragma: 'no-cache',
          'sec-fetch-dest': 'empty',
          'sec-fetch-mode': 'cors',
          'sec-fetch-site': 'same-origin',
          'User-Agent':
            'Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0',
          'x-api-key': API_KEY,
        },
      })

      if (!response.ok) {
        throw new Error(
          `BMKG API Error: ${response.status} ${response.statusText}`,
        )
      }

      const data = await response.json()
      return data
    } catch (error) {
      console.error('BMKG API fetch failed:', error)
      throw error
    }
  }

  // async getForecast(lat: number, lon: number): Promise<BMKGResponse> {
  //   console.log({ lat, lon })
  //   const fakeData = {
  //     lokasi: {
  //       adm1: '31',
  //       adm2: '31.71',
  //       adm3: '31.71.07',
  //       adm4: '31.71.07.1005',
  //       provinsi: 'DKI Jakarta',
  //       kotkab: 'Kota Adm. Jakarta Pusat',
  //       kecamatan: 'Tanah Abang',
  //       desa: 'Kebon Melati',
  //       lon: 106.81596823959143,
  //       lat: -6.197052719903746,
  //       distance: 0,
  //       timezone: 'Asia/Jakarta',
  //     },
  //     data: [
  //       {
  //         lokasi: {
  //           adm1: '31',
  //           adm2: '31.71',
  //           adm3: '31.71.07',
  //           adm4: '31.71.07.1005',
  //           provinsi: 'DKI Jakarta',
  //           kotkab: 'Kota Adm. Jakarta Pusat',
  //           kecamatan: 'Tanah Abang',
  //           desa: 'Kebon Melati',
  //           lon: 106.8159682396,
  //           lat: -6.1970527199,
  //           timezone: '+0700',
  //           type: 'adm4',
  //         },
  //         cuaca: [
  //           [
  //             {
  //               datetime: '2026-01-25T05:00:00Z',
  //               t: 29,
  //               tcc: 100,
  //               tp: 0.2,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 334,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 12.8,
  //               hu: 71,
  //               vs: 21768,
  //               vs_text: '> 10 km',
  //               time_index: '4-5',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-25 05:00:00',
  //               local_datetime: '2026-01-25 12:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T06:00:00Z',
  //               t: 29,
  //               tcc: 100,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 334,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 12.8,
  //               hu: 70,
  //               vs: 21768,
  //               vs_text: '> 10 km',
  //               time_index: '5-6',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-25 06:00:00',
  //               local_datetime: '2026-01-25 13:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T07:00:00Z',
  //               t: 29,
  //               tcc: 100,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 332,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 9.8,
  //               hu: 72,
  //               vs: 25529,
  //               vs_text: '> 10 km',
  //               time_index: '6-7',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-25 07:00:00',
  //               local_datetime: '2026-01-25 14:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T08:00:00Z',
  //               t: 29,
  //               tcc: 98,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 332,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 9.8,
  //               hu: 74,
  //               vs: 25529,
  //               vs_text: '> 10 km',
  //               time_index: '7-8',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-25 08:00:00',
  //               local_datetime: '2026-01-25 15:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T09:00:00Z',
  //               t: 28,
  //               tcc: 99,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 332,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 9.8,
  //               hu: 76,
  //               vs: 25529,
  //               vs_text: '> 10 km',
  //               time_index: '8-9',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-25 09:00:00',
  //               local_datetime: '2026-01-25 16:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T10:00:00Z',
  //               t: 27,
  //               tcc: 99,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 337,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 3.1,
  //               hu: 81,
  //               vs: 29127,
  //               vs_text: '> 10 km',
  //               time_index: '9-10',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-25 10:00:00',
  //               local_datetime: '2026-01-25 17:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T11:00:00Z',
  //               t: 27,
  //               tcc: 100,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 337,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 3.1,
  //               hu: 85,
  //               vs: 29127,
  //               vs_text: '> 10 km',
  //               time_index: '10-11',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-25 11:00:00',
  //               local_datetime: '2026-01-25 18:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T12:00:00Z',
  //               t: 26,
  //               tcc: 99,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 337,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 3.1,
  //               hu: 88,
  //               vs: 29127,
  //               vs_text: '> 10 km',
  //               time_index: '11-12',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-25 12:00:00',
  //               local_datetime: '2026-01-25 19:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T13:00:00Z',
  //               t: 26,
  //               tcc: 99,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 292,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 1.6,
  //               hu: 88,
  //               vs: 32021,
  //               vs_text: '> 10 km',
  //               time_index: '12-13',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-25 13:00:00',
  //               local_datetime: '2026-01-25 20:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T14:00:00Z',
  //               t: 26,
  //               tcc: 99,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 292,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 1.6,
  //               hu: 87,
  //               vs: 32021,
  //               vs_text: '> 10 km',
  //               time_index: '13-14',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-25 14:00:00',
  //               local_datetime: '2026-01-25 21:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T15:00:00Z',
  //               t: 25,
  //               tcc: 100,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 292,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 1.6,
  //               hu: 90,
  //               vs: 32021,
  //               vs_text: '> 10 km',
  //               time_index: '14-15',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-25 15:00:00',
  //               local_datetime: '2026-01-25 22:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T16:00:00Z',
  //               t: 25,
  //               tcc: 100,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 13,
  //               wd: 'N',
  //               wd_to: 'S',
  //               ws: 1,
  //               hu: 92,
  //               vs: 15666,
  //               vs_text: '> 10 km',
  //               time_index: '15-16',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-25 16:00:00',
  //               local_datetime: '2026-01-25 23:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-01-25T17:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 13,
  //               wd: 'N',
  //               wd_to: 'S',
  //               ws: 1,
  //               hu: 93,
  //               vs: 15666,
  //               vs_text: '> 10 km',
  //               time_index: '16-17',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-25 17:00:00',
  //               local_datetime: '2026-01-26 00:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T18:00:00Z',
  //               t: 24,
  //               tcc: 99,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 13,
  //               wd: 'N',
  //               wd_to: 'S',
  //               ws: 1,
  //               hu: 94,
  //               vs: 15666,
  //               vs_text: '> 10 km',
  //               time_index: '17-18',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-25 18:00:00',
  //               local_datetime: '2026-01-26 01:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T19:00:00Z',
  //               t: 24,
  //               tcc: 64,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 259,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 1.8,
  //               hu: 95,
  //               vs: 11551,
  //               vs_text: '> 10 km',
  //               time_index: '18-19',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-25 19:00:00',
  //               local_datetime: '2026-01-26 02:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T20:00:00Z',
  //               t: 24,
  //               tcc: 75,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 259,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 1.8,
  //               hu: 95,
  //               vs: 11551,
  //               vs_text: '> 10 km',
  //               time_index: '19-20',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-25 20:00:00',
  //               local_datetime: '2026-01-26 03:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T21:00:00Z',
  //               t: 24,
  //               tcc: 74,
  //               tp: 0.1,
  //               weather: 2,
  //               weather_desc: 'Cerah Berawan',
  //               weather_desc_en: 'Partly Cloudy',
  //               wd_deg: 259,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 1.8,
  //               hu: 94,
  //               vs: 11551,
  //               vs_text: '> 10 km',
  //               time_index: '20-21',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-pm.svg',
  //               utc_datetime: '2026-01-25 21:00:00',
  //               local_datetime: '2026-01-26 04:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T22:00:00Z',
  //               t: 24,
  //               tcc: 77,
  //               tp: 0.1,
  //               weather: 2,
  //               weather_desc: 'Cerah Berawan',
  //               weather_desc_en: 'Partly Cloudy',
  //               wd_deg: 225,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 3.5,
  //               hu: 94,
  //               vs: 8017,
  //               vs_text: '< 9 km',
  //               time_index: '21-22',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-pm.svg',
  //               utc_datetime: '2026-01-25 22:00:00',
  //               local_datetime: '2026-01-26 05:00:00',
  //             },
  //             {
  //               datetime: '2026-01-25T23:00:00Z',
  //               t: 25,
  //               tcc: 98,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 225,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 3.5,
  //               hu: 90,
  //               vs: 8017,
  //               vs_text: '< 9 km',
  //               time_index: '22-23',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-25 23:00:00',
  //               local_datetime: '2026-01-26 06:00:00',
  //             },
  //             {
  //               datetime: '2026-01-26T00:00:00Z',
  //               t: 26,
  //               tcc: 83,
  //               tp: 0.1,
  //               weather: 2,
  //               weather_desc: 'Cerah Berawan',
  //               weather_desc_en: 'Partly Cloudy',
  //               wd_deg: 225,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 3.5,
  //               hu: 86,
  //               vs: 8017,
  //               vs_text: '< 9 km',
  //               time_index: '23-24',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-am.svg',
  //               utc_datetime: '2026-01-26 00:00:00',
  //               local_datetime: '2026-01-26 07:00:00',
  //             },
  //             {
  //               datetime: '2026-01-26T03:00:00Z',
  //               t: 28,
  //               tcc: 100,
  //               tp: 0.2,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 325,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 11.2,
  //               hu: 72,
  //               vs: 10127,
  //               vs_text: '> 10 km',
  //               time_index: '26-27',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-26 03:00:00',
  //               local_datetime: '2026-01-26 10:00:00',
  //             },
  //             {
  //               datetime: '2026-01-26T06:00:00Z',
  //               t: 29,
  //               tcc: 100,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 331,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 13.8,
  //               hu: 70,
  //               vs: 17653,
  //               vs_text: '> 10 km',
  //               time_index: '29-30',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-26 06:00:00',
  //               local_datetime: '2026-01-26 13:00:00',
  //             },
  //             {
  //               datetime: '2026-01-26T09:00:00Z',
  //               t: 28,
  //               tcc: 100,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 328,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 10.4,
  //               hu: 74,
  //               vs: 20938,
  //               vs_text: '> 10 km',
  //               time_index: '32-33',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-26 09:00:00',
  //               local_datetime: '2026-01-26 16:00:00',
  //             },
  //             {
  //               datetime: '2026-01-26T12:00:00Z',
  //               t: 27,
  //               tcc: 100,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 4,
  //               wd: 'N',
  //               wd_to: 'S',
  //               ws: 3.3,
  //               hu: 86,
  //               vs: 33486,
  //               vs_text: '> 10 km',
  //               time_index: '35-36',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-26 12:00:00',
  //               local_datetime: '2026-01-26 19:00:00',
  //             },
  //             {
  //               datetime: '2026-01-26T15:00:00Z',
  //               t: 25,
  //               tcc: 100,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 292,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 1.6,
  //               hu: 90,
  //               vs: 14485,
  //               vs_text: '> 10 km',
  //               time_index: '38-39',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-26 15:00:00',
  //               local_datetime: '2026-01-26 22:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-01-26T18:00:00Z',
  //               t: 25,
  //               tcc: 100,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 303,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 3.3,
  //               hu: 90,
  //               vs: 22281,
  //               vs_text: '> 10 km',
  //               time_index: '41-42',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-26 18:00:00',
  //               local_datetime: '2026-01-27 01:00:00',
  //             },
  //             {
  //               datetime: '2026-01-26T21:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 2.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 304,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 1.4,
  //               hu: 92,
  //               vs: 6386,
  //               vs_text: '< 7 km',
  //               time_index: '44-45',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-26 21:00:00',
  //               local_datetime: '2026-01-27 04:00:00',
  //             },
  //             {
  //               datetime: '2026-01-27T00:00:00Z',
  //               t: 25,
  //               tcc: 99,
  //               tp: 1.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 231,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 5,
  //               hu: 89,
  //               vs: 6970,
  //               vs_text: '< 7 km',
  //               time_index: '47-48',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-27 00:00:00',
  //               local_datetime: '2026-01-27 07:00:00',
  //             },
  //             {
  //               datetime: '2026-01-27T03:00:00Z',
  //               t: 27,
  //               tcc: 99,
  //               tp: 1.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 335,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 9.2,
  //               hu: 78,
  //               vs: 25331,
  //               vs_text: '> 10 km',
  //               time_index: '50-51',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-27 03:00:00',
  //               local_datetime: '2026-01-27 10:00:00',
  //             },
  //             {
  //               datetime: '2026-01-27T06:00:00Z',
  //               t: 28,
  //               tcc: 99,
  //               tp: 3,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 335,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 9.2,
  //               hu: 74,
  //               vs: 25331,
  //               vs_text: '> 10 km',
  //               time_index: '53-54',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-27 06:00:00',
  //               local_datetime: '2026-01-27 13:00:00',
  //             },
  //             {
  //               datetime: '2026-01-27T09:00:00Z',
  //               t: 26,
  //               tcc: 100,
  //               tp: 3,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 210,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 3.7,
  //               hu: 84,
  //               vs: 12508,
  //               vs_text: '> 10 km',
  //               time_index: '56-57',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-27 09:00:00',
  //               local_datetime: '2026-01-27 16:00:00',
  //             },
  //             {
  //               datetime: '2026-01-27T12:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 1.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 210,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 3.7,
  //               hu: 94,
  //               vs: 12508,
  //               vs_text: '> 10 km',
  //               time_index: '59-60',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-27 12:00:00',
  //               local_datetime: '2026-01-27 19:00:00',
  //             },
  //             {
  //               datetime: '2026-01-27T15:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 1.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 206,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 6.4,
  //               hu: 95,
  //               vs: 5610,
  //               vs_text: '< 6 km',
  //               time_index: '62-63',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-27 15:00:00',
  //               local_datetime: '2026-01-27 22:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-01-27T18:00:00Z',
  //               t: 23,
  //               tcc: 100,
  //               tp: 0.3,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 206,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 6.4,
  //               hu: 95,
  //               vs: 5610,
  //               vs_text: '< 6 km',
  //               time_index: '65-66',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-27 18:00:00',
  //               local_datetime: '2026-01-28 01:00:00',
  //             },
  //             {
  //               datetime: '2026-01-27T21:00:00Z',
  //               t: 23,
  //               tcc: 100,
  //               tp: 0.3,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 152,
  //               wd: 'SE',
  //               wd_to: 'NW',
  //               ws: 5,
  //               hu: 96,
  //               vs: 10751,
  //               vs_text: '> 10 km',
  //               time_index: '68-69',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-27 21:00:00',
  //               local_datetime: '2026-01-28 04:00:00',
  //             },
  //             {
  //               datetime: '2026-01-28T00:00:00Z',
  //               t: 25,
  //               tcc: 100,
  //               tp: 0.4,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 152,
  //               wd: 'SE',
  //               wd_to: 'NW',
  //               ws: 5,
  //               hu: 89,
  //               vs: 10751,
  //               vs_text: '> 10 km',
  //               time_index: '71-72',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-28 00:00:00',
  //               local_datetime: '2026-01-28 07:00:00',
  //             },
  //             {
  //               datetime: '2026-01-28T03:00:00Z',
  //               t: 28,
  //               tcc: 100,
  //               tp: 0.4,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 334,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 13.2,
  //               hu: 73,
  //               vs: 20110,
  //               vs_text: '> 10 km',
  //               time_index: '74-75',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-28 03:00:00',
  //               local_datetime: '2026-01-28 10:00:00',
  //             },
  //             {
  //               datetime: '2026-01-28T06:00:00Z',
  //               t: 28,
  //               tcc: 100,
  //               tp: 1.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 334,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 13.2,
  //               hu: 75,
  //               vs: 20110,
  //               vs_text: '> 10 km',
  //               time_index: '77-78',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-28 06:00:00',
  //               local_datetime: '2026-01-28 13:00:00',
  //             },
  //             {
  //               datetime: '2026-01-28T09:00:00Z',
  //               t: 28,
  //               tcc: 100,
  //               tp: 1.7,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 331,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 2.1,
  //               hu: 75,
  //               vs: 6721,
  //               vs_text: '< 7 km',
  //               time_index: '80-81',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-28 09:00:00',
  //               local_datetime: '2026-01-28 16:00:00',
  //             },
  //             {
  //               datetime: '2026-01-28T12:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 5.8,
  //               weather: 63,
  //               weather_desc: 'Hujan Sedang',
  //               weather_desc_en: 'Moderate Rain',
  //               wd_deg: 331,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 2.1,
  //               hu: 96,
  //               vs: 6721,
  //               vs_text: '< 7 km',
  //               time_index: '83-84',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan sedang-pm.svg',
  //               utc_datetime: '2026-01-28 12:00:00',
  //               local_datetime: '2026-01-28 19:00:00',
  //             },
  //             {
  //               datetime: '2026-01-28T15:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 5.8,
  //               weather: 63,
  //               weather_desc: 'Hujan Sedang',
  //               weather_desc_en: 'Moderate Rain',
  //               wd_deg: 176,
  //               wd: 'SE',
  //               wd_to: 'NW',
  //               ws: 6.8,
  //               hu: 96,
  //               vs: 7047,
  //               vs_text: '< 8 km',
  //               time_index: '86-87',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan sedang-pm.svg',
  //               utc_datetime: '2026-01-28 15:00:00',
  //               local_datetime: '2026-01-28 22:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-01-28T18:00:00Z',
  //               t: 23,
  //               tcc: 100,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 176,
  //               wd: 'SE',
  //               wd_to: 'NW',
  //               ws: 6.8,
  //               hu: 96,
  //               vs: 7047,
  //               vs_text: '< 8 km',
  //               time_index: '89-90',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-28 18:00:00',
  //               local_datetime: '2026-01-29 01:00:00',
  //             },
  //             {
  //               datetime: '2026-01-28T21:00:00Z',
  //               t: 23,
  //               tcc: 100,
  //               tp: 0.1,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 197,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 2,
  //               hu: 94,
  //               vs: 12287,
  //               vs_text: '> 10 km',
  //               time_index: '92-93',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-28 21:00:00',
  //               local_datetime: '2026-01-29 04:00:00',
  //             },
  //             {
  //               datetime: '2026-01-29T00:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 1.5,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 197,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 2,
  //               hu: 92,
  //               vs: 12287,
  //               vs_text: '> 10 km',
  //               time_index: '95-96',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-29 00:00:00',
  //               local_datetime: '2026-01-29 07:00:00',
  //             },
  //             {
  //               datetime: '2026-01-29T06:00:00Z',
  //               t: 27,
  //               tcc: 100,
  //               tp: 1.5,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 82,
  //               wd: 'NE',
  //               wd_to: 'SW',
  //               ws: 0.4,
  //               hu: 80,
  //               vs: 22492,
  //               vs_text: '> 10 km',
  //               time_index: '101-102',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-am.svg',
  //               utc_datetime: '2026-01-29 06:00:00',
  //               local_datetime: '2026-01-29 13:00:00',
  //             },
  //             {
  //               datetime: '2026-01-29T12:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 1.5,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 82,
  //               wd: 'NE',
  //               wd_to: 'SW',
  //               ws: 0.4,
  //               hu: 91,
  //               vs: 22492,
  //               vs_text: '> 10 km',
  //               time_index: '107-108',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-29 12:00:00',
  //               local_datetime: '2026-01-29 19:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-01-29T18:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 1.5,
  //               weather: 61,
  //               weather_desc: 'Hujan Ringan',
  //               weather_desc_en: 'Light Rain',
  //               wd_deg: 217,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 5,
  //               hu: 95,
  //               vs: 17753,
  //               vs_text: '> 10 km',
  //               time_index: '113-114',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/hujan ringan-pm.svg',
  //               utc_datetime: '2026-01-29 18:00:00',
  //               local_datetime: '2026-01-30 01:00:00',
  //             },
  //             {
  //               datetime: '2026-01-30T00:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 0.4,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 217,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 5,
  //               hu: 92,
  //               vs: 17753,
  //               vs_text: '> 10 km',
  //               time_index: '119-120',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-30 00:00:00',
  //               local_datetime: '2026-01-30 07:00:00',
  //             },
  //             {
  //               datetime: '2026-01-30T06:00:00Z',
  //               t: 29,
  //               tcc: 88,
  //               tp: 0.4,
  //               weather: 2,
  //               weather_desc: 'Cerah Berawan',
  //               weather_desc_en: 'Partly Cloudy',
  //               wd_deg: 256,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 7.7,
  //               hu: 72,
  //               vs: 6297,
  //               vs_text: '< 7 km',
  //               time_index: '125-126',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-am.svg',
  //               utc_datetime: '2026-01-30 06:00:00',
  //               local_datetime: '2026-01-30 13:00:00',
  //             },
  //             {
  //               datetime: '2026-01-30T12:00:00Z',
  //               t: 25,
  //               tcc: 100,
  //               tp: 0.6,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 256,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 7.7,
  //               hu: 88,
  //               vs: 6297,
  //               vs_text: '< 7 km',
  //               time_index: '131-132',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-30 12:00:00',
  //               local_datetime: '2026-01-30 19:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-01-30T18:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 0.6,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 200,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 4.9,
  //               hu: 96,
  //               vs: 19937,
  //               vs_text: '> 10 km',
  //               time_index: '137-138',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-30 18:00:00',
  //               local_datetime: '2026-01-31 01:00:00',
  //             },
  //             {
  //               datetime: '2026-01-31T00:00:00Z',
  //               t: 24,
  //               tcc: 51,
  //               tp: 0.3,
  //               weather: 1,
  //               weather_desc: 'Cerah',
  //               weather_desc_en: 'Sunny',
  //               wd_deg: 200,
  //               wd: 'S',
  //               wd_to: 'N',
  //               ws: 4.9,
  //               hu: 91,
  //               vs: 19937,
  //               vs_text: '> 10 km',
  //               time_index: '143-144',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg',
  //               utc_datetime: '2026-01-31 00:00:00',
  //               local_datetime: '2026-01-31 07:00:00',
  //             },
  //             {
  //               datetime: '2026-01-31T06:00:00Z',
  //               t: 29,
  //               tcc: 100,
  //               tp: 0.3,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 247,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 2.5,
  //               hu: 72,
  //               vs: 24852,
  //               vs_text: '> 10 km',
  //               time_index: '149-150',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-01-31 06:00:00',
  //               local_datetime: '2026-01-31 13:00:00',
  //             },
  //             {
  //               datetime: '2026-01-31T12:00:00Z',
  //               t: 26,
  //               tcc: 100,
  //               tp: 0.2,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 247,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 2.5,
  //               hu: 87,
  //               vs: 24852,
  //               vs_text: '> 10 km',
  //               time_index: '155-156',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-31 12:00:00',
  //               local_datetime: '2026-01-31 19:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-01-31T18:00:00Z',
  //               t: 24,
  //               tcc: 100,
  //               tp: 0.2,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 252,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 4.8,
  //               hu: 91,
  //               vs: 9576,
  //               vs_text: '< 10 km',
  //               time_index: '161-162',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-01-31 18:00:00',
  //               local_datetime: '2026-02-01 01:00:00',
  //             },
  //             {
  //               datetime: '2026-02-01T00:00:00Z',
  //               t: 24,
  //               tcc: 92,
  //               tp: 0.4,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 252,
  //               wd: 'SW',
  //               wd_to: 'NE',
  //               ws: 4.8,
  //               hu: 91,
  //               vs: 9576,
  //               vs_text: '< 10 km',
  //               time_index: '167-168',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-02-01 00:00:00',
  //               local_datetime: '2026-02-01 07:00:00',
  //             },
  //             {
  //               datetime: '2026-02-01T06:00:00Z',
  //               t: 30,
  //               tcc: 61,
  //               tp: 0.4,
  //               weather: 2,
  //               weather_desc: 'Cerah Berawan',
  //               weather_desc_en: 'Partly Cloudy',
  //               wd_deg: 284,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 1.1,
  //               hu: 67,
  //               vs: 30754,
  //               vs_text: '> 10 km',
  //               time_index: '173-174',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-am.svg',
  //               utc_datetime: '2026-02-01 06:00:00',
  //               local_datetime: '2026-02-01 13:00:00',
  //             },
  //             {
  //               datetime: '2026-02-01T12:00:00Z',
  //               t: 26,
  //               tcc: 100,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 284,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 1.1,
  //               hu: 87,
  //               vs: 30754,
  //               vs_text: '> 10 km',
  //               time_index: '179-180',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-02-01 12:00:00',
  //               local_datetime: '2026-02-01 19:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-02-01T18:00:00Z',
  //               t: 25,
  //               tcc: 31,
  //               tp: 0,
  //               weather: 1,
  //               weather_desc: 'Cerah',
  //               weather_desc_en: 'Sunny',
  //               wd_deg: 272,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 5.3,
  //               hu: 91,
  //               vs: 30408,
  //               vs_text: '> 10 km',
  //               time_index: '185-186',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg',
  //               utc_datetime: '2026-02-01 18:00:00',
  //               local_datetime: '2026-02-02 01:00:00',
  //             },
  //             {
  //               datetime: '2026-02-02T00:00:00Z',
  //               t: 25,
  //               tcc: 14,
  //               tp: 0.4,
  //               weather: 1,
  //               weather_desc: 'Cerah',
  //               weather_desc_en: 'Sunny',
  //               wd_deg: 272,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 5.3,
  //               hu: 91,
  //               vs: 30408,
  //               vs_text: '> 10 km',
  //               time_index: '191-192',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg',
  //               utc_datetime: '2026-02-02 00:00:00',
  //               local_datetime: '2026-02-02 07:00:00',
  //             },
  //             {
  //               datetime: '2026-02-02T06:00:00Z',
  //               t: 30,
  //               tcc: 97,
  //               tp: 0.4,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 340,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 4.9,
  //               hu: 69,
  //               vs: 21502,
  //               vs_text: '> 10 km',
  //               time_index: '197-198',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-02-02 06:00:00',
  //               local_datetime: '2026-02-02 13:00:00',
  //             },
  //             {
  //               datetime: '2026-02-02T12:00:00Z',
  //               t: 27,
  //               tcc: 37,
  //               tp: 0,
  //               weather: 1,
  //               weather_desc: 'Cerah',
  //               weather_desc_en: 'Sunny',
  //               wd_deg: 340,
  //               wd: 'NW',
  //               wd_to: 'SE',
  //               ws: 4.9,
  //               hu: 87,
  //               vs: 21502,
  //               vs_text: '> 10 km',
  //               time_index: '203-204',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg',
  //               utc_datetime: '2026-02-02 12:00:00',
  //               local_datetime: '2026-02-02 19:00:00',
  //             },
  //           ],
  //           [
  //             {
  //               datetime: '2026-02-02T18:00:00Z',
  //               t: 25,
  //               tcc: 100,
  //               tp: 0,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 289,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 4.6,
  //               hu: 92,
  //               vs: 30895,
  //               vs_text: '> 10 km',
  //               time_index: '209-210',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg',
  //               utc_datetime: '2026-02-02 18:00:00',
  //               local_datetime: '2026-02-03 01:00:00',
  //             },
  //             {
  //               datetime: '2026-02-03T00:00:00Z',
  //               t: 24,
  //               tcc: 99,
  //               tp: 0.2,
  //               weather: 3,
  //               weather_desc: 'Berawan',
  //               weather_desc_en: 'Mostly Cloudy',
  //               wd_deg: 289,
  //               wd: 'W',
  //               wd_to: 'E',
  //               ws: 4.6,
  //               hu: 92,
  //               vs: 30895,
  //               vs_text: '> 10 km',
  //               time_index: '215-216',
  //               analysis_date: '2026-01-25T00:00:00',
  //               image:
  //                 'https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-am.svg',
  //               utc_datetime: '2026-02-03 00:00:00',
  //               local_datetime: '2026-02-03 07:00:00',
  //             },
  //           ],
  //         ],
  //       },
  //     ],
  //   }

  //   return Promise.resolve(fakeData as BMKGResponse)
  // }
}
